import turtle
leo = turtle.Turtle()
leo.shape("turtle")
leo.pensize(3)

for i in range(1):
    leo.pencolor("black")
    leo.fillcolor("red")
    leo.begin_fill()
    leo.up()
    leo.goto(-300, 150)
    leo.down()
    for _ in range(2):
        leo.forward(150)
        leo.right(90)
        leo.forward(300)
        leo.right(90)
    leo.end_fill()

    leo.fillcolor("red")
    leo.begin_fill()
    leo.up()
    leo.goto(150, 150)
    leo.down()
    for _ in range(2):
        leo.forward(150)
        leo.right(90)
        leo.forward(300)
        leo.right(90)
    leo.end_fill()

    leo.fillcolor("white")
    leo.begin_fill()
    leo.up()
    leo.goto(-150, 150)
    leo.down()
    for _ in range(2):
        leo.forward(300)
        leo.right(90)
        leo.forward(300)
        leo.right(90)
    leo.end_fill()
    
    leo.penup()
    leo.goto(0, -50)
    leo.pendown()
    
leo.pencolor('red')
leo.fillcolor('red')   
leo.begin_fill()
leo.left(90)

leo.right(105)
leo.forward(70)   
leo.left(120)
leo.forward(20)
leo.right(85)
leo.forward(60)
leo.left(120)
leo.forward(20)
leo.right(85)
leo.forward(50)
leo.left(130)
leo.forward(50)
leo.right(90)
leo.forward(20)
leo.left(120)
leo.forward(60)
leo.right(130)
leo.forward(80)
leo.left(120)
leo.forward(20)
leo.right(90)
leo.forward(50)
leo.left(130)
leo.forward(50)
leo.right(90)
leo.forward(20) 
leo.left(120)
leo.forward(80)
leo.right(130)
leo.forward(60)
leo.left(120)
leo.forward(20)
leo.right(90)
leo.forward(50)
leo.left(130)
leo.forward(50)
leo.right(90)
leo.forward(20)
leo.left(120)
leo.forward(50)
leo.right(85)
leo.forward(20)
leo.left(120)
leo.forward(75)   
leo.end_fill()

leo.penup()
leo.goto(0,-50)
leo.pendown()
leo.pencolor('red')
leo.fillcolor('red')
leo.begin_fill()
for i in range(2):
        leo.backward(6)
        leo.left(80)
        leo.backward(50)
        leo.left(100)
leo.end_fill()

leo.hideturtle()
turtle.exitonclick()

#bandeira do canáda
# COMPONENTES:
#LUZIA GRAZIELLY G. DE CARVALHO
#TYFANY VIVIANE DA COSTA